apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-telemetry-query-service
  namespace: axion-app
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1


  selector:
    matchLabels:
      app: axion-telemetry-query-service

  template:
    metadata:
      labels:
        app: axion-telemetry-query-service

    spec:
      containers:
      - name: axion-telemetry-query-service
        image: acrtodoappjay.azurecr.io/axion-telemetry-query-service:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://jaydeepc1985:Oneday%40321@axion-ingestion-service:5432/axion-db"