apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-telemetry-query-service
  namespace: axion-app
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1


  selector:
    matchLabels:
      app: axion-telemetry-query-service

  template:
    metadata:
      labels:
        app: axion-telemetry-query-service

    spec:
      containers:
      - name: axion-telemetry-query-service
        image: acrtodoappjay.azurecr.io/axion-telemetry-query-service:v2
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secrets-store-query
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: DATABASE--URL
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: db-url
      volumes:
      - name: secrets-store-query
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv"
